name: Ping Render Service

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Loop to Ping Render
        run: |
          for i in {1..2}; do
            echo "$(date) - Pinging Render URL"
            curl -I "https://code-cell-website-fv8m.onrender.com"
            sleep 600  # Wait for 10 minutes (600 seconds) between pings
          done
